// Generated by Claude
using System;
using System.IO;
using UnityEngine;

namespace TTModdingKit.Helper
{
    /// <summary>
    /// Utility class for converting between Unity Texture2D and DDS file format.
    /// Supports DXT1 and DXT5 on output. DXT3 input is supported by transcoding to DXT5,
    /// since Unity has no DXT3 TextureFormat.
    /// </summary>
    public static class DDSConvert
    {
        // DDS Magic number: "DDS " (0x20534444)
        private const uint DDS_MAGIC = 0x20534444;

        // DDSD flags
        private const uint DDSD_CAPS = 0x00000001;
        private const uint DDSD_HEIGHT = 0x00000002;
        private const uint DDSD_WIDTH = 0x00000004;
        private const uint DDSD_PIXELFORMAT = 0x00001000;
        private const uint DDSD_LINEARSIZE = 0x00080000;
        private const uint DDSD_MIPMAPCOUNT = 0x00020000;

        // DDSCAPS flags
        private const uint DDSCAPS_TEXTURE = 0x00001000;
        private const uint DDSCAPS_MIPMAP = 0x00400000;
        private const uint DDSCAPS_COMPLEX = 0x00000008;

        // DDPF flags
        private const uint DDPF_FOURCC = 0x00000004;

        // FourCC codes
        private const uint FOURCC_DXT1 = 0x31545844; // "DXT1"
        private const uint FOURCC_DXT3 = 0x33545844; // "DXT3"
        private const uint FOURCC_DXT5 = 0x35545844; // "DXT5"

        // DDS header is always 128 bytes: 4 (magic) + 124 (header struct)
        private const int DDS_HEADER_SIZE = 128;

        #region Texture2D to DDS

        /// <summary>
        /// Converts a Unity Texture2D to a DDS byte array.
        /// The texture must use a DXT1 or DXT5 format (Unity has no DXT3 output).
        /// </summary>
        /// <param name="texture">The source Texture2D. Must be DXT compressed.</param>
        /// <param name="includeMipmaps">Whether to include mipmaps in the output.</param>
        /// <returns>A byte array representing the DDS file.</returns>
        public static byte[] TextureToDDSBytes(this Texture2D texture, bool includeMipmaps = true)
        {
            if (texture == null)
                throw new ArgumentNullException(nameof(texture));

            uint fourCC = GetFourCC(texture.format);

            int mipCount = includeMipmaps ? texture.mipmapCount : 1;
            bool hasMipmaps = mipCount > 1;

            using var ms = new MemoryStream();
            using var writer = new BinaryWriter(ms);

            // Magic
            writer.Write(DDS_MAGIC);

            // DDSURFACEDESC2 (124 bytes)
            uint flags = DDSD_CAPS | DDSD_HEIGHT | DDSD_WIDTH | DDSD_PIXELFORMAT | DDSD_LINEARSIZE;
            if (hasMipmaps) flags |= DDSD_MIPMAPCOUNT;

            writer.Write(124u);             // dwSize
            writer.Write(flags);            // dwFlags
            writer.Write((uint)texture.height);
            writer.Write((uint)texture.width);

            // dwPitchOrLinearSize — size of the top-level mip's compressed data
            uint linearSize = CalculateDXTSize(fourCC, texture.width, texture.height);
            writer.Write(linearSize);

            writer.Write(0u);               // dwDepth
            writer.Write((uint)mipCount);  // dwMipMapCount

            // dwReserved1 (11 DWORDs)
            for (int i = 0; i < 11; i++)
                writer.Write(0u);

            // DDPIXELFORMAT (32 bytes)
            writer.Write(32u);              // ddpf.dwSize
            writer.Write(DDPF_FOURCC);      // ddpf.dwFlags
            writer.Write(fourCC);           // ddpf.dwFourCC
            writer.Write(0u);               // dwRGBBitCount
            writer.Write(0u);               // dwRBitMask
            writer.Write(0u);               // dwGBitMask
            writer.Write(0u);               // dwBBitMask
            writer.Write(0u);               // dwABitMask

            // DDSCAPS2 (16 bytes)
            uint caps = DDSCAPS_TEXTURE;
            if (hasMipmaps) caps |= DDSCAPS_MIPMAP | DDSCAPS_COMPLEX;
            writer.Write(caps);
            writer.Write(0u);               // dwCaps2
            writer.Write(0u);               // dwCaps3
            writer.Write(0u);               // dwCaps4

            writer.Write(0u);               // dwReserved2

            // Pixel data for each mip level
            for (int mip = 0; mip < mipCount; mip++)
            {
                byte[] mipData = texture.GetRawTextureData();

                if (mipCount == 1)
                {
                    // Single mip — write all raw data directly
                    writer.Write(mipData);
                    break;
                }

                // For multi-mip, we need per-mip data. Unity doesn't expose per-mip
                // bytes directly, so we compute the offset manually.
                int mipWidth = Mathf.Max(1, texture.width >> mip);
                int mipHeight = Mathf.Max(1, texture.height >> mip);
                uint mipSize = CalculateDXTSize(fourCC, mipWidth, mipHeight);

                // Calculate byte offset for this mip level within the raw data
                int offset = 0;
                for (int m = 0; m < mip; m++)
                {
                    int mw = Mathf.Max(1, texture.width >> m);
                    int mh = Mathf.Max(1, texture.height >> m);
                    offset += (int)CalculateDXTSize(fourCC, mw, mh);
                }

                writer.Write(mipData, offset, (int)mipSize);
            }

            return ms.ToArray();
        }

        /// <summary>
        /// Converts a Unity Texture2D to a DDS file and saves it to disk.
        /// </summary>
        /// <param name="texture">The source Texture2D. Must be DXT compressed.</param>
        /// <param name="outputPath">Full path where the .dds file will be written.</param>
        /// <param name="includeMipmaps">Whether to include mipmaps in the output.</param>
        public static void TextureToDDSFile(this Texture2D texture, string outputPath, bool includeMipmaps = true)
        {
            if (string.IsNullOrEmpty(outputPath))
                throw new ArgumentException("Output path must not be null or empty.", nameof(outputPath));

            byte[] ddsBytes = TextureToDDSBytes(texture, includeMipmaps);
            File.WriteAllBytes(outputPath, ddsBytes);
        }

        #endregion

        #region DDS to Texture2D

        /// <summary>
        /// Converts a DDS byte array into a Unity Texture2D.
        /// Supports DXT1, DXT3, and DXT5 formats.
        /// </summary>
        /// <param name="ddsBytes">Raw bytes of a DDS file.</param>
        /// <param name="filterMode">The filter mode to apply to the resulting texture.</param>
        /// <param name="wrapMode">The wrap mode to apply to the resulting texture.</param>
        /// <returns>A new Texture2D loaded with the DDS data.</returns>
        public static Texture2D DDSBytesToTexture(
            byte[] ddsBytes,
            FilterMode filterMode = FilterMode.Bilinear,
            TextureWrapMode wrapMode = TextureWrapMode.Repeat)
        {
            if (ddsBytes == null || ddsBytes.Length < DDS_HEADER_SIZE)
                throw new ArgumentException("Invalid or too-short DDS byte array.", nameof(ddsBytes));

            using var reader = new BinaryReader(new MemoryStream(ddsBytes));

            // Validate magic
            uint magic = reader.ReadUInt32();
            if (magic != DDS_MAGIC)
                throw new InvalidDataException($"Not a valid DDS file. Magic: 0x{magic:X8}");

            // DDSURFACEDESC2
            uint headerSize = reader.ReadUInt32();
            if (headerSize != 124)
                throw new InvalidDataException($"Unexpected DDS header size: {headerSize}. Expected 124.");

            uint flags = reader.ReadUInt32();
            int height = (int)reader.ReadUInt32();
            int width = (int)reader.ReadUInt32();
            uint linearSize = reader.ReadUInt32(); // dwPitchOrLinearSize
            uint depth = reader.ReadUInt32(); // dwDepth (unused for 2D)
            int mipCount = (int)reader.ReadUInt32();
            if (mipCount < 1) mipCount = 1;

            // Skip dwReserved1 (11 DWORDs = 44 bytes)
            reader.BaseStream.Seek(44, SeekOrigin.Current);

            // DDPIXELFORMAT
            uint pfSize = reader.ReadUInt32();
            uint pfFlags = reader.ReadUInt32();
            uint fourCC = reader.ReadUInt32();

            // Skip remaining pixel format fields (5 DWORDs = 20 bytes)
            reader.BaseStream.Seek(20, SeekOrigin.Current);

            // DDSCAPS (16 bytes)
            reader.BaseStream.Seek(16, SeekOrigin.Current);

            // dwReserved2
            reader.BaseStream.Seek(4, SeekOrigin.Current);

            // Map FourCC --> Unity TextureFormat (DXT3 maps to DXT5 after transcoding)
            TextureFormat textureFormat = FourCCToTextureFormat(fourCC);

            // Read all remaining bytes as raw pixel data
            int dataLength = ddsBytes.Length - DDS_HEADER_SIZE;
            byte[] pixelData = reader.ReadBytes(dataLength);

            // DXT3 is not a valid Unity TextureFormat — transcode each mip level to DXT5
            if (fourCC == FOURCC_DXT3)
                pixelData = TranscodeDXT3ToDXT5AllMips(pixelData, width, height, mipCount);

            bool hasMipmaps = (mipCount > 1);
            var texture = new Texture2D(width, height, textureFormat, hasMipmaps);
            texture.filterMode = filterMode;
            texture.wrapMode = wrapMode;

            texture.LoadRawTextureData(pixelData);
            texture.Apply(hasMipmaps, false);

            return texture;
        }

        /// <summary>
        /// Loads a DDS file from disk and converts it into a Unity Texture2D.
        /// Supports DXT1, DXT3, and DXT5 formats.
        /// </summary>
        /// <param name="filePath">Full path to the .dds file.</param>
        /// <param name="filterMode">The filter mode to apply to the resulting texture.</param>
        /// <param name="wrapMode">The wrap mode to apply to the resulting texture.</param>
        /// <returns>A new Texture2D loaded with the DDS data.</returns>
        public static Texture2D DDSFileToTexture(
            string filePath,
            FilterMode filterMode = FilterMode.Bilinear,
            TextureWrapMode wrapMode = TextureWrapMode.Repeat)
        {
            if (string.IsNullOrEmpty(filePath))
                throw new ArgumentException("File path must not be null or empty.", nameof(filePath));

            if (!File.Exists(filePath))
                throw new FileNotFoundException("DDS file not found.", filePath);

            byte[] ddsBytes = File.ReadAllBytes(filePath);
            return DDSBytesToTexture(ddsBytes, filterMode, wrapMode);
        }

        #endregion

        #region Private Helpers

        /// <summary>
        /// Returns the DDS FourCC code for a given Unity TextureFormat.
        /// Unity does not have a DXT3 TextureFormat, so only DXT1 and DXT5 are supported for output.
        /// </summary>
        private static uint GetFourCC(TextureFormat format)
        {
            return format switch
            {
                TextureFormat.DXT1 => FOURCC_DXT1,
                TextureFormat.DXT5 => FOURCC_DXT5,
                _ => throw new NotSupportedException(
                    $"Texture format '{format}' is not supported for DDS output. " +
                    $"Unity only supports DXT1 and DXT5 as writable compressed formats.")
            };
        }

        /// <summary>
        /// Maps a DDS FourCC to a Unity TextureFormat.
        /// DXT3 is not a valid Unity TextureFormat, so callers must check for it separately
        /// and use TranscodeDXT3ToDXT5 before creating the texture.
        /// </summary>
        private static TextureFormat FourCCToTextureFormat(uint fourCC)
        {
            return fourCC switch
            {
                FOURCC_DXT1 => TextureFormat.DXT1,
                // DXT3 is handled via transcoding before this is called
                FOURCC_DXT3 => TextureFormat.DXT5,
                FOURCC_DXT5 => TextureFormat.DXT5,
                _ => throw new NotSupportedException(
                    $"Unsupported DDS FourCC: 0x{fourCC:X8}. " +
                    $"Only DXT1 (0x{FOURCC_DXT1:X8}), DXT3 (0x{FOURCC_DXT3:X8}), " +
                    $"and DXT5 (0x{FOURCC_DXT5:X8}) are supported.")
            };
        }

        /// <summary>
        /// Transcodes all mip levels in a DXT3 raw buffer to DXT5.
        /// Since DXT3 and DXT5 use the same block size (16 bytes), the output is the same length.
        /// </summary>
        private static byte[] TranscodeDXT3ToDXT5AllMips(byte[] dxt3Data, int baseWidth, int baseHeight, int mipCount)
        {
            using var inStream = new MemoryStream(dxt3Data);
            using var outStream = new MemoryStream(dxt3Data.Length); // same total size

            for (int mip = 0; mip < mipCount; mip++)
            {
                int mipWidth = Mathf.Max(1, baseWidth >> mip);
                int mipHeight = Mathf.Max(1, baseHeight >> mip);
                int mipBytes = (int)CalculateDXTSize(FOURCC_DXT3, mipWidth, mipHeight); // 16 bytes/block

                byte[] mipSrc = new byte[mipBytes];
                inStream.Read(mipSrc, 0, mipBytes);

                byte[] mipDst = TranscodeDXT3ToDXT5(mipSrc, mipWidth, mipHeight);
                outStream.Write(mipDst, 0, mipDst.Length);
            }

            return outStream.ToArray();
        }

        /// <summary>
        /// Transcodes a raw DXT3 pixel buffer to DXT5.
        /// <para>
        /// Both formats use 16 bytes per 4×4 block:
        ///   DXT3 block layout: [8 bytes explicit 4-bit alpha] [8 bytes DXT1 color]
        ///   DXT5 block layout: [8 bytes interpolated alpha]   [8 bytes DXT1 color]
        /// The color block is identical between the two formats; only the alpha block changes.
        /// </para>
        /// </summary>
        private static byte[] TranscodeDXT3ToDXT5(byte[] dxt3Data, int width, int height)
        {
            // Block count — same for both formats (16 bytes/block each)
            int blocksWide = Mathf.Max(1, (width + 3) / 4);
            int blocksTall = Mathf.Max(1, (height + 3) / 4);
            int blockCount = blocksWide * blocksTall;

            byte[] dxt5Data = new byte[blockCount * 16];

            for (int i = 0; i < blockCount; i++)
            {
                int srcOffset = i * 16;
                int dstOffset = i * 16;

                // --- Decode DXT3 explicit alpha (8 bytes, 16 x 4-bit values) ---
                // Each nibble is one pixel's alpha, ranging 0–15 --> scale to 0–255.
                byte[] alphas = new byte[16];
                for (int b = 0; b < 8; b++)
                {
                    byte byteVal = dxt3Data[srcOffset + b];
                    alphas[b * 2] = (byte)((byteVal & 0x0F) * 17); // 0–15 --> 0–255
                    alphas[b * 2 + 1] = (byte)((byteVal >> 4) * 17);
                }

                // --- Encode DXT5 interpolated alpha block ---
                // Choose alpha0 and alpha1 to span the full range present in the block.
                byte minA = 255, maxA = 0;
                foreach (byte a in alphas) { if (a < minA) minA = a; if (a > maxA) maxA = a; }

                dxt5Data[dstOffset] = maxA; // alpha0 (larger --> 6-value mode)
                dxt5Data[dstOffset + 1] = minA; // alpha1

                // Build the 6 interpolated values (indices 0 and 1 are alpha0/alpha1)
                byte[] interp = new byte[8];
                interp[0] = maxA;
                interp[1] = minA;
                if (maxA > minA)
                {
                    // 6-interpolated-value mode (alpha0 > alpha1)
                    for (int k = 2; k <= 7; k++)
                        interp[k] = (byte)(((8 - k) * maxA + (k - 1) * minA + 3) / 7);
                }
                else
                {
                    // Edge case: all alpha equal — just fill with alpha0
                    for (int k = 2; k <= 7; k++)
                        interp[k] = maxA;
                }

                // Pack 16 x 3-bit indices into 6 bytes
                ulong indexBits = 0;
                for (int p = 0; p < 16; p++)
                {
                    int bestIdx = 0;
                    int bestDist = int.MaxValue;
                    for (int k = 0; k < 8; k++)
                    {
                        int dist = Math.Abs(alphas[p] - interp[k]);
                        if (dist < bestDist) { bestDist = dist; bestIdx = k; }
                    }
                    indexBits |= ((ulong)bestIdx << (p * 3));
                }

                // Write the 6 index bytes
                for (int b = 0; b < 6; b++)
                    dxt5Data[dstOffset + 2 + b] = (byte)((indexBits >> (b * 8)) & 0xFF);

                // --- Copy color block unchanged (bytes 8–15) ---
                Array.Copy(dxt3Data, srcOffset + 8, dxt5Data, dstOffset + 8, 8);
            }

            return dxt5Data;
        }

        /// <summary>
        /// Calculates the byte size of a single DXT-compressed mip level.
        /// DXT1 uses 8 bytes per 4x4 block; DXT3/DXT5 use 16 bytes per 4x4 block.
        /// </summary>
        private static uint CalculateDXTSize(uint fourCC, int width, int height)
        {
            int blockSize = (fourCC == FOURCC_DXT1) ? 8 : 16;
            int blocksWide = Mathf.Max(1, (width + 3) / 4);
            int blocksTall = Mathf.Max(1, (height + 3) / 4);
            return (uint)(blocksWide * blocksTall * blockSize);
        }

        #endregion
    }
}